name: Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${GITHUB_TOKEN}"\
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/OWNER/REPO/releases \
              -d '{"tag_name":"latest","target_commitish":"main","name":"latest","body":"Latest","draft":true,"prerelease":false,"generate_release_notes":false}'

